name: Lint
on: push

jobs:
    black:
        name: Black
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - uses: jpetrucciani/black-check@master
    prettier:
        name: Prettier
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-prettier
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - run: npm install -g prettier@3.5.3
            - run: |-
                  prettier --check .
